version: "3.7"

volumes:
  postgres_data:

networks:
  backend:
  frontend:

services:
  postgres:
    image: postgres:10-alpine
    ports:
    - published: ${EJ3_PGPORT:-5432}
      target: 5432
    volumes:
    - type: volume
      source: postgres_data
      target: /var/lib/postgresql/data
    networks:
    - backend
    environment:
      POSTGRES_PASSWORD: 3x4mpl3P455w0rd

  backend_test: &backend
    image: vovimayhem/ejercicio3-backend:development
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    volumes:
    - type: bind
      source: ./backend
      target: /usr/src

    stdin_open: true
    tty: true

    entrypoint: /usr/src/bin/dev-entrypoint.sh
    networks:
    - backend
    depends_on:
    - postgres
    environment: &backend_env
      RACK_ENV: test
      RAILS_ENV: test
      RAILS_LOG_TO_STDOUT: "true"
      DATABASE_URL: postgres://postgres:3x4mpl3P455w0rd@postgres:5432/demo_test

  backend_web:
    <<: *backend
    command: ["rails", "server", "-b", "0.0.0.0", "-p", "3000"]
    entrypoint: /usr/src/bin/dev-entrypoint.sh
    networks:
    - backend
    - frontend
    ports:
    - published: ${EJ3_BACKEND_WEB_PORT:-3000}
      target: 3000
    environment:
      <<: *backend_env
      RACK_ENV: development
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:3x4mpl3P455w0rd@postgres:5432/demo_development

  # ================================================================================================
  # Containers / Services for the Frontend App:
  frontend_test: &frontend_app
    image: vovimayhem/ejercicio3-frontend:development
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    volumes:
    - type: bind
      source: ./frontend
      target: /usr/src
    entrypoint: /usr/src/bin/dev-entrypoint.sh
    command: ember test --server
    ports:
      - ${EJ3_FRONTEND_TEST_PORT:-7357}:7357
    environment: &frontend_env
      DEMO_BACKEND_URL: ${DEMO_BACKEND_URL:-http://localhost:3000}

  frontend_web:
    <<: *frontend_app
    command: ember server --live-reload-port 35730
    networks:
    - frontend
    ports:
    - published: ${EJ3_FRONTEND_WEB_PORT:-4200}
      target: 4200
    - published: ${EJ3_FRONTEND_LIVE_RELOAD_PORT:-35730}
      target: 35730
    depends_on:
      - backend_web
    stdin_open: true
    tty: true
    environment:
      <<: *frontend_env
      DEMO_BACKEND_URL_ON_BACKEND: ${DEMO_BACKEND_URL_ON_BACKEND:-http://backend_web:3000}
